import { Box, Container, Flex } from '@chakra-ui/react';
import Head from 'next/head';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';
import Section1 from '../components/Section1';
import Section2 from '../components/Section2';
import Section3 from '../components/Section3';
import WidthWrapper from '../components/WidthWrapper';

export default function Home() {
    return (
        <Flex alignItems='center' flexDir='column'>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
                <link rel='preconnect' href='https://fonts.googleapis.com' />
                <link
                    rel='preconnect'
                    href='https://fonts.gstatic.com'
                    crossOrigin
                />
                <link
                    rel='preload'
                    as='style'
                    href='https://fonts.googleapis.com/css2?family=Overpass:wght@300;600&family=Ubuntu:wght@400;500;700&display=swap'
                />
                <link
                    href='https://fonts.googleapis.com/css2?family=Overpass:wght@300;600&family=Ubuntu:wght@400;500;700&display=swap'
                    rel='stylesheet'
                    media='print'
                    onLoad="this.media='all'"
                />
                <noscript>
                    <link
                        href='https://fonts.googleapis.com/css2?family=Overpass:wght@300;600&family=Ubuntu:wght@400;500;700&display=swap'
                        rel='stylesheet'
                    />
                </noscript>
            </Head>
            <Header />
            <WidthWrapper>
                <Section1 />
            </WidthWrapper>
            <Section2 />
            <WidthWrapper>
                <Section3 />
            </WidthWrapper>

            <Footer />
        </Flex>
    );
}
